### ISSUE TITLE
Focus pseudo-class použitie

### ISSUE THREAD

**Issue by ViktoriaAndr** [VendulaKonecna/PROJEKT-Cukrarna#1]
https://github.com/VendulaKonecna/PROJEKT-Cukrarna/blob/ff527a3df95f90a45e2e46cb445ca9ecb91549e3/style.css#L67
Ahoj,
načo tam máš prosím ten focus? Prechádzam položky v menu a pri hover-ovaní sa zafarbí pole - to je ok, keď kliknem, tak ostane focus na jednom z položiek, ale bez toho, aby som klikla ďalšiu poožku alebo inam, to pole ostane zafarbené. Pokiaľ by ma to hodilo na tú časť webu, tak je to z UX hľadiska OK, ale takto ma to len poplietlo. Inak technicky to chyba nie je.

Pekne spravený dobrovoľný úkol :)

**Comment by VendulaKonecna** [comment]
Ahoj,
všimla jsem si až teď, že jsi mi sem psala Issue.
Dělala jsem to tenkrát s pomocí komentovaného řešení k projektu Boty, co jsme dostali od Luďka a má to tam použitý. Asi jsem to brala tak, že je to označení zrovna aktivní stránku. Ale teď mi došlo, že na to je :active 🤭 
Děkuji za upozornění, už jsem si dohledala, jaký je mezitím rozdíl.

**Comment by ViktoriaAndr** [comment]
super, ďakujem za odpoveď, uzatváram
